on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      #- run: git fetch --no-tags --prune --depth=5 origin main

      - uses: actions/setup-node@v2.1.0
        with:
          node-version: 12

      - run: yarn install --frozen-lockfile

      - run: yarn affected:lint --base={{ github.base_ref }} --head={{ github.head_ref }}
      - run: yarn affected:test --base={{ github.base_ref }} --head={{ github.head_ref }}
      - run: yarn affected:e2e --base={{ github.base_ref }} --head={{ github.head_ref }}
      - run: yarn affected:build --base={{ github.base_ref }} --head={{ github.head_ref }}
