on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.0
        with:
          node-version: 12

      - run: yarn install --frozen-lockfile

      - run: yarn nx run-many --parallel --all --target=lint
      - run: yarn nx run-many --parallel --all --target=test
      - run: yarn nx run-many --parallel --all --target=e2e
      - run: yarn nx run-many --parallel --all --target=build
