on:
  push:
  pull_request_target:
jobs:
  move-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: olivr/copybara-action@v1.2.2
        with:
          ssh_key: ${{ secrets.GH_SSH_BOT }}
          access_token: ${{ secrets.GH_TOKEN_BOT }}
          sot_repo: olivr/nx-copybara
          destination_repo: olivr/nx-copybara-todos
          push_include: '.github/workflows/build-pr.yml .github/workflows/move-code.yml apps/todos*/** libs/** externals/todos/** tools/** .*rc .*ignore *.json *.js *.lock'
          push_exclude: 'nx.json tsconfig.base.json workspace.json'
          pr_move: |
            nx.json||externals/todos/nx.json
            tsconfig.base.json||externals/todos/tsconfig.base.json
            workspace.json||externals/todos/workspace.json
